In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("extracted_data.csv")
print(df.iloc[5793])

File Path    ../data/maildir/lavorato-j/calendar/9.
Date          Thu, 25 Jan 2001 06:33:59 -0800 (PST)
From                               hillis@enron.com
To                                              NaN
Name: 5793, dtype: str

In [3]:
df.rename(columns={"Date": "Date_Time"}, inplace=True)
df["Date"] = df['Date_Time'].str.split().str[:4].str.join(" ")
display(df.head())

,File Path,Date_Time,From,To,Date
0,../data/maildir/arnold-j/notes_inbox/36.,"Thu, 16 Nov 2000 09:30:00 -0800 (PST)",msagel@home.com,jarnold@enron.com,"Thu, 16 Nov 2000"
1,../data/maildir/arnold-j/notes_inbox/19.,"Fri, 8 Dec 2000 05:05:00 -0800 (PST)",slafontaine@globalp.com,john.arnold@enron.com,"Fri, 8 Dec 2000"
2,../data/maildir/arnold-j/notes_inbox/50.,"Tue, 15 May 2001 09:43:00 -0700 (PDT)",iceoperations@intcx.com,"icehelpdesk@intcx.com, internalmarketing@intcx...","Tue, 15 May 2001"
3,../data/maildir/arnold-j/notes_inbox/3.,"Mon, 27 Nov 2000 01:49:00 -0800 (PST)",jeff.youngflesh@enron.com,"anthony.gilmore@enron.com, colleen.koenig@enro...","Mon, 27 Nov 2000"
4,../data/maildir/arnold-j/notes_inbox/9.,"Tue, 12 Dec 2000 09:33:00 -0800 (PST)",caroline.abramo@enron.com,mike.grigsby@enron.com,"Tue, 12 Dec 2000"

In [4]:
perfect_pattern = r'^[A-Za-z]{3},\s\d{1,2}\s[A-Za-z]{3}\s\d{4}$'
exceptions_mask = ~df['Date'].str.match(perfect_pattern, na=False)

print(f"Found {exceptions_mask.sum()} exceptions. Here they are:")
display(df[exceptions_mask][['Date_Time', 'Date']])

Found 0 exceptions. Here they are:

Empty DataFrame
Columns: [Date_Time, Date]
Index: []